# Generated by Django 5.0.6 on 2024-05-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairecours',
            name='Cours_Package',
        ),
        migrations.RemoveField(
            model_name='commentairecours',
            name='Cours_Unite',
        ),
        migrations.RemoveField(
            model_name='commentairecours',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='commentairecours',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='commentairecours',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='montant',
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='cour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cours'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentairecours',
            name='contenu',
            field=models.TextField(help_text='Entrez le contenu du commentaire (entre 10 et 5000 caractères).'),
        ),
        migrations.AlterField(
            model_name='commentairecours',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='prixdebasepackage',
            name='type',
            field=models.CharField(default='package', max_length=50, unique=True),
        ),
    ]
