# Generated by Django 4.2.11 on 2024-04-09 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='professeurs',
            field=models.ManyToManyField(related_name='matieres', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='discussionprofadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_avec_prof', to='user.admin'),
        ),
        migrations.AddField(
            model_name='discussionprofadmin',
            name='messages',
            field=models.ManyToManyField(related_name='messages_prof_admin', to='api.message'),
        ),
        migrations.AddField(
            model_name='discussionprofadmin',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_avec_admin', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='discussionparentadmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_avec_parent', to='user.admin'),
        ),
        migrations.AddField(
            model_name='discussionparentadmin',
            name='messages',
            field=models.ManyToManyField(related_name='messages_parent_admin', to='api.message'),
        ),
        migrations.AddField(
            model_name='discussionparentadmin',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_avec_admin', to='user.parent'),
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='api.matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.cours'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.matiere'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_parent', to='user.parent'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_professeur', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='activitebloquee',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activite'),
        ),
        migrations.AddField(
            model_name='activite',
            name='participants',
            field=models.ManyToManyField(related_name='activites', to=settings.AUTH_USER_MODEL),
        ),
    ]
