# Generated by Django 5.0.6 on 2024-05-18 16:01

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_package',
            name='selected_disponibilites',
            field=jsonfield.fields.JSONField(blank=True, help_text='Disponibilités sélectionnées', null=True),
        ),
        migrations.AlterField(
            model_name='cours_package',
            name='heures_par_semaine',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'heures par semaine"),
        ),
    ]
