# Generated by Django 5.0.3 on 2024-04-30 12:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('present', models.BooleanField(default=False)),
                ('dispense', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.eleve')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=api.models.upload_to)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_planifies', models.IntegerField(default=0)),
                ('cours_effectues', models.IntegerField(default=0)),
                ('cours_manques', models.IntegerField(default=0)),
                ('professeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.professeur')),
            ],
        ),
    ]
