# Generated by Django 5.0.6 on 2024-05-23 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours_package',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='cours_unite',
            name='parent',
        ),
        migrations.AddField(
            model_name='cours_package',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours_unite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
