# Generated by Django 5.0.3 on 2024-05-21 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_parent', to='user.parent'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_professeur', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='cours',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.eleve'),
        ),
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='cours_package',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.parent'),
        ),
        migrations.AddField(
            model_name='cours_package',
            name='professeur',
            field=models.ForeignKey(blank=True, help_text='Professeur', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='cours_unite',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.parent'),
        ),
        migrations.AddField(
            model_name='cours_unite',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_unite', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='coursrattrapage',
            name='cours_manque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours'),
        ),
        migrations.AddField(
            model_name='coursrattrapage',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursreserve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursreserve',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='user.eleve'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='user.professeur'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='api.categorie'),
        ),
        migrations.AddField(
            model_name='cours_unite',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.matiere'),
        ),
        migrations.AddField(
            model_name='cours_package',
            name='matiere',
            field=models.ForeignKey(help_text='Matière du cours', on_delete=django.db.models.deletion.PROTECT, to='api.matiere'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.matiere'),
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='cours_manque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suiviprofesseur',
            name='professeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.parent'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professeur'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
