# Generated by Django 5.0.6 on 2024-05-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cours_package_selected_disponibilites_and_more'),
        ('user', '0003_professeur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_package',
            name='professeur',
            field=models.ForeignKey(blank=True, help_text='Professeur', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.professeur'),
        ),
    ]
