# Generated by Django 5.0.3 on 2024-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours_package',
            old_name='durée',
            new_name='duree',
        ),
        migrations.RenameField(
            model_name='cours_unite',
            old_name='matière',
            new_name='matiere',
        ),
        migrations.AlterField(
            model_name='cours_unite',
            name='lieu_des_cours',
            field=models.CharField(choices=[('la_maison', 'La maison'), ('a_distance', 'À distance')], max_length=50),
        ),
    ]
