# Generated by Django 5.0.6 on 2024-05-25 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_commentairecours_cours_package_and_more'),
        ('user', '0002_professeur_matieres_a_enseigner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Cour',
        ),
    ]
