# Generated by Django 5.0.6 on 2024-05-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cours_package_professeur'),
        ('user', '0003_professeur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_package',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.parent'),
        ),
        migrations.AlterField(
            model_name='cours_package',
            name='est_actif',
            field=models.BooleanField(default=False, help_text='Le forfait est-il actuellement actif ?'),
        ),
    ]
