# Generated by Django 5.0.6 on 2024-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cours_cour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_unite',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cours_unite',
            name='heure_fine',
            field=models.TimeField(null=True),
        ),
    ]
