# Generated by Django 5.0.3 on 2024-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cours_unite_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('EC', 'En cours'), ('AV', 'A venir'), ('T', 'Terminer'), ('A', 'Annulé')], default='AV', max_length=2),
        ),
    ]
