# Generated by Django 5.0.6 on 2024-05-19 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cours_package_parent_alter_cours_package_est_actif'),
        ('user', '0005_parent_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_unite',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent', null=True, on_delete=django.db.models.deletion.PROTECT, to='user.parent'),
        ),
    ]
