# Generated by Django 5.0.6 on 2024-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cours_unite_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='annule',
            field=models.BooleanField(default=False),
        ),
    ]
