# Generated by Django 5.0.6 on 2024-05-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cours_unite_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixDeBasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('prix_par_semaine', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('prix_par_eleve', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
            ],
        ),
    ]
