# Generated by Django 5.0.6 on 2024-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cour_annule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='annule',
        ),
        migrations.AddField(
            model_name='cour',
            name='statut',
            field=models.CharField(choices=[('AV', 'A venir'), ('T', 'Terminer'), ('A', 'Annulé')], default='AV', max_length=2),
        ),
    ]
