# Generated by Django 5.0.6 on 2024-05-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cour_annule_cour_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='present',
        ),
    ]
