# Generated by Django 5.0.6 on 2024-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prixdebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixdebase',
            name='prix_par_eleve',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='prixdebase',
            name='prix_par_semaine',
            field=models.FloatField(default=100.0),
        ),
    ]
