# Generated by Django 5.0.6 on 2024-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_prix_par_semaine_prixdebase_prix_par_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
