# Generated by Django 5.0.6 on 2024-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cours_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_unite',
            name='sujet',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
