# Generated by Django 5.0.6 on 2024-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='matieres_a_enseigner',
            field=models.ManyToManyField(to='api.matiere'),
        ),
    ]
