# Generated by Django 4.2.11 on 2024-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
    ]
