# Generated by Django 5.0.3 on 2024-04-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_parent_latitude_parent_longitude_enfant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enfant',
            table='user_enfant',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pourcentage_intermediaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_recues', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
