# Generated by Django 5.0.6 on 2024-05-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_professeur_matiere_a_enseigner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
