# Generated by Django 4.2.11 on 2024-04-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_parent_latitude_alter_parent_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
