# Generated by Django 5.0.6 on 2024-05-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_professeur_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
