# Generated by Django 5.0.6 on 2024-05-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_parent_date_naissance_eleve_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
